class_name FormRegistry
extends RefCounted
## DCSS transmutation / talisman form catalog. Lazy-loads the 30-ish
## forms generated by `tools/convert_dcss_forms.py`. Each entry carries
## the mechanical deltas (hp_mod, stats, AC, unarmed damage, resists)
## plus feature flags (can_fly, can_swim) that drive terrain checks.
##
## Actual form application is in Player.apply_form / clear_form — this
## is just the data layer.

const _JSON: String = "res://assets/dcss_forms/forms.json"

static var _data: Dictionary = {}
static var _loaded: bool = false


static func _ensure_loaded() -> void:
	if _loaded:
		return
	_loaded = true
	var f := FileAccess.open(_JSON, FileAccess.READ)
	if f == null:
		push_warning("FormRegistry: missing %s" % _JSON)
		return
	var parsed = JSON.parse_string(f.get_as_text())
	f.close()
	if typeof(parsed) == TYPE_DICTIONARY:
		_data = parsed


static func has(id: String) -> bool:
	_ensure_loaded()
	return _data.has(id)


static func get_info(id: String) -> Dictionary:
	_ensure_loaded()
	return _data.get(id, {}).duplicate() if _data.has(id) else {}


static func all_ids() -> Array:
	_ensure_loaded()
	return _data.keys()
