class_name UnrandartRegistry
extends Object
## DCSS-inspired unique named artifacts (unrandarts). Unlike regular
## randarts, unrands have hand-crafted stats and flavor text — seeing
## "the Singing Sword" means the same sword every run.
##
## Implementation: each entry carries the base weapon/armor/ring data
## shape the existing registries expect, so WeaponRegistry /
## ArmorRegistry / RingRegistry / AmuletRegistry fall through to us
## when the id has an "unrand_" prefix. No new equip pathway needed.
##
## Effect coverage uses existing brand / ego mechanics — we're not
## porting special per-unrand routines (Singing Sword's warbling,
## Krishna's arrow storm). A unique is a fixed base + plus + brand/ego
## combo with distinctive flavor naming, not a new code path.

const _UNRANDS: Dictionary = {
	# ---------------- WEAPONS ----------------
	"unrand_singing_sword": {
		"kind": "weapon",
		"base": "longsword",
		"name": "the Singing Sword",
		"dmg": 10, "skill": "long_blade", "delay": 1.3,
		"plus": 7, "brand": "holy_wrath",
		"color": Color(1.00, 0.90, 0.45),
		"min_depth": 8,
		"desc": "A long sword that hums in combat, slicing through unholy foes.",
	},
	"unrand_bow_of_krishna": {
		"kind": "weapon",
		"base": "longbow",
		"name": "the Bow of Krishna",
		"dmg": 16, "skill": "bow", "delay": 1.6,
		"plus": 5, "brand": "flaming",
		"color": Color(1.00, 0.55, 0.25),
		"min_depth": 10,
		"desc": "Arrows loosed from this bow burst into divine flame.",
	},
	"unrand_plutonium_sword": {
		"kind": "weapon",
		"base": "great_sword",
		"name": "the Plutonium Sword",
		"dmg": 15, "skill": "long_blade", "delay": 1.7,
		"plus": 4, "brand": "chaos",
		"color": Color(0.75, 1.00, 0.45),
		"min_depth": 12,
		"desc": "Every swing unleashes a different radiant horror on the target.",
	},
	"unrand_mace_of_variability": {
		"kind": "weapon",
		"base": "mace",
		"name": "the Mace of Variability",
		"dmg": 11, "skill": "mace", "delay": 1.4,
		"plus": 5, "brand": "chaos",
		"color": Color(0.85, 0.55, 0.95),
		"min_depth": 8,
		"desc": "The mace shimmers and distorts, never striking the same way twice.",
	},
	"unrand_wucad_mu_staff": {
		"kind": "weapon",
		"base": "staff",
		"name": "Wucad Mu's Staff",
		"dmg": 8, "skill": "staff", "delay": 1.3,
		"plus": 5, "brand": "pain",
		"color": Color(0.55, 0.30, 0.70),
		"min_depth": 10,
		"desc": "A gnarled staff that drinks life force from every foe it touches.",
	},
	"unrand_skullcrusher": {
		"kind": "weapon",
		"base": "great_mace",
		"name": "Skullcrusher",
		"dmg": 17, "skill": "mace", "delay": 1.9,
		"plus": 6, "brand": "vorpal",
		"color": Color(0.90, 0.85, 0.75),
		"min_depth": 12,
		"desc": "A two-handed mace that caves in helms and skulls alike.",
	},
	"unrand_storm_bow": {
		"kind": "weapon",
		"base": "shortbow",
		"name": "the Storm Bow",
		"dmg": 10, "skill": "bow", "delay": 1.3,
		"plus": 4, "brand": "electrocution",
		"color": Color(0.70, 0.85, 1.00),
		"min_depth": 7,
		"desc": "Each arrow crackles with storm-lightning on release.",
	},

	# ---------------- BODY ARMOUR ----------------
	"unrand_robe_of_augmentation": {
		"kind": "armor",
		"base": "robe",
		"name": "the Robe of Augmentation",
		"slot": "chest",
		"ac": 2, "plus": 3, "ego": "resistance",
		"color": Color(1.00, 0.85, 0.55),
		"min_depth": 8,
		"desc": "A silken robe that subtly bolsters the wearer's elemental wards.",
	},

	# ---------------- CLOAK ----------------
	"unrand_cloak_of_the_thief": {
		"kind": "armor",
		"base": "cloak",
		"name": "the Cloak of the Thief",
		"slot": "cloak",
		"ac": 1, "plus": 3, "ego": "stealth",
		"color": Color(0.35, 0.35, 0.45),
		"min_depth": 6,
		"desc": "A dark cloak that seems to drink the torchlight around it.",
	},

	# ---------------- HELM ----------------
	"unrand_hat_of_the_alchemist": {
		"kind": "armor",
		"base": "hat",
		"name": "the Hat of the Alchemist",
		"slot": "helm",
		"ac": 1, "plus": 2, "ego": "poison_resistance",
		"color": Color(0.60, 0.95, 0.55),
		"min_depth": 6,
		"desc": "A pointed hat soaked in fumes that steel the wearer against venoms.",
	},

	# ---------------- RING ----------------
	"unrand_ring_of_shaolin": {
		"kind": "ring",
		"name": "the Ring of Shaolin",
		"color": Color(0.95, 0.75, 0.35),
		"min_depth": 7,
		"slot": "ring",
		"desc": "A lacquered wooden ring — worn by monks seeking inner balance.",
		# Ring props use the same shape as RandartGenerator output so the
		# equip path folds them in via _recompute_gear_stats.
		"props": {"ev": 5, "dex": 2, "stealth": 2},
	},

	# ---------------- AMULET ----------------
	"unrand_amulet_of_bloodlust": {
		"kind": "amulet",
		"name": "the Amulet of Bloodlust",
		"color": Color(0.85, 0.15, 0.15),
		"min_depth": 8,
		"slot": "amulet",
		"base": "amulet_acrobat",  # reuses the acrobat passive as a proxy
		"desc": "Worn on the neck, it whispers of endless battle.",
		"props": {"str": 2, "slaying": 3},
	},

	# ---------------- WAVE 2 (+10, session 15) ----------------
	# Weapons
	"unrand_finisher": {
		"kind": "weapon",
		"base": "scimitar",
		"name": "Finisher",
		"dmg": 12, "skill": "long_blade", "delay": 1.2,
		"plus": 5, "brand": "speed",
		"color": Color(0.95, 0.95, 0.30),
		"min_depth": 9,
		"desc": "A slender blade whose strikes arrive before the swing.",
	},
	"unrand_sword_of_cerebov": {
		"kind": "weapon",
		"base": "great_sword",
		"name": "the Sword of Cerebov",
		"dmg": 22, "skill": "long_blade", "delay": 1.8,
		"plus": 6, "brand": "flaming",
		"color": Color(1.00, 0.35, 0.10),
		"min_depth": 18,
		"desc": "Cerebov's twisted blade drips with infernal flame.",
	},
	"unrand_obsidian_axe": {
		"kind": "weapon",
		"base": "waraxe",
		"name": "the Obsidian Axe",
		"dmg": 15, "skill": "axe", "delay": 1.5,
		"plus": 6, "brand": "pain",
		"color": Color(0.10, 0.05, 0.20),
		"min_depth": 14,
		"desc": "A black glass axe that feeds on suffering.",
	},
	"unrand_spriggans_rapier": {
		"kind": "weapon",
		"base": "rapier",
		"name": "Spriggan's Rapier",
		"dmg": 7, "skill": "short_blade", "delay": 1.0,
		"plus": 4, "brand": "venom",
		"color": Color(0.70, 1.00, 0.45),
		"min_depth": 7,
		"desc": "A wee envenomed rapier — light enough to flick between heartbeats.",
	},
	"unrand_vampire_tooth": {
		"kind": "weapon",
		"base": "dagger",
		"name": "the Vampire's Tooth",
		"dmg": 5, "skill": "short_blade", "delay": 0.9,
		"plus": 5, "brand": "pain",
		"color": Color(0.85, 0.15, 0.40),
		"min_depth": 8,
		"desc": "A dagger carved from a vampire's fang — drinks vitality on every cut.",
	},

	# Armor
	"unrand_crystal_plate": {
		"kind": "armor",
		"base": "crystal_plate_armour",
		"name": "the Crystal Plate of the Starlit Seer",
		"slot": "chest",
		"ac": 14, "plus": 4, "ego": "archmagi",
		"color": Color(0.75, 0.85, 1.00),
		"min_depth": 16,
		"desc": "Heavy plate shot through with mana-conducting crystals.",
	},
	"unrand_troll_skin_of_the_north": {
		"kind": "armor",
		"base": "troll_leather_armour",
		"name": "the Troll Skin of the North",
		"slot": "chest",
		"ac": 4, "plus": 5, "ego": "cold_resistance",
		"color": Color(0.55, 0.70, 0.95),
		"min_depth": 10,
		"desc": "Bitterly cold troll hide that regenerates the wearer.",
	},

	# Boots / Gloves
	"unrand_boots_of_the_assassin": {
		"kind": "armor",
		"base": "boots",
		"name": "the Boots of the Assassin",
		"slot": "boots",
		"ac": 1, "plus": 3, "ego": "stealth",
		"color": Color(0.20, 0.20, 0.30),
		"min_depth": 7,
		"desc": "Silent as grave-dust. The wearer barely registers on prey.",
	},
	"unrand_gauntlets_of_war": {
		"kind": "armor",
		"base": "gloves",
		"name": "the Gauntlets of War",
		"slot": "gloves",
		"ac": 2, "plus": 3, "ego": "strength",
		"color": Color(0.85, 0.50, 0.20),
		"min_depth": 9,
		"desc": "Iron gauntlets that flood the wearer with raw strength.",
	},

	# Ring
	"unrand_ring_of_the_octopus_king": {
		"kind": "ring",
		"name": "the Ring of the Octopus King",
		"color": Color(0.55, 0.25, 0.85),
		"min_depth": 11,
		"slot": "ring",
		"desc": "One of the legendary rings of the Octopus King — a touch of all magics.",
		"props": {"str": 1, "dex": 1, "int": 1, "ac": 2, "ev": 2, "slaying": 2},
	},

	# ---------------- WAVE 3 (+13, session 15) ----------------
	# --- Weapons ---
	"unrand_giant_club_of_stomping": {
		"kind": "weapon",
		"base": "giant_club",
		"name": "the Giant Club of Stomping",
		"dmg": 25, "skill": "mace", "delay": 2.2,
		"plus": 3, "brand": "heavy",
		"color": Color(0.75, 0.55, 0.30),
		"min_depth": 14,
		"desc": "Ogrish thunder in wood form. Crushes through armour.",
	},
	"unrand_woodcutters_axe": {
		"kind": "weapon",
		"base": "axe_medium",
		"name": "the Woodcutter's Axe",
		"dmg": 13, "skill": "axe", "delay": 1.5,
		"plus": 4, "brand": "vorpal",
		"color": Color(0.55, 0.40, 0.25),
		"min_depth": 8,
		"desc": "A well-worn axe that cleaves wood and bone alike.",
	},
	"unrand_punk": {
		"kind": "weapon",
		"base": "dagger",
		"name": "Punk",
		"dmg": 5, "skill": "short_blade", "delay": 0.8,
		"plus": 3, "brand": "electrocution",
		"color": Color(0.95, 0.85, 0.35),
		"min_depth": 5,
		"desc": "A short, sparking shiv pulled from a street fight.",
	},
	"unrand_snake_sceptre": {
		"kind": "weapon",
		"base": "staff",
		"name": "the Snake Sceptre",
		"dmg": 9, "skill": "staff", "delay": 1.3,
		"plus": 4, "brand": "venom",
		"color": Color(0.40, 0.85, 0.30),
		"min_depth": 11,
		"desc": "A serpent-coiled staff that spits poison with every strike.",
	},
	"unrand_frostbite": {
		"kind": "weapon",
		"base": "flail",
		"name": "Frostbite",
		"dmg": 11, "skill": "mace", "delay": 1.4,
		"plus": 5, "brand": "freezing",
		"color": Color(0.65, 0.85, 1.00),
		"min_depth": 9,
		"desc": "Ice forms on the chain between swings.",
	},
	"unrand_spellbinder": {
		"kind": "weapon",
		"base": "staff",
		"name": "the Spellbinder",
		"dmg": 8, "skill": "staff", "delay": 1.2,
		"plus": 5, "brand": "antimagic",
		"color": Color(0.75, 0.50, 0.90),
		"min_depth": 10,
		"desc": "A staff that drains magic from any caster it touches.",
	},

	# --- Armor / Aux ---
	"unrand_armour_of_zhor": {
		"kind": "armor",
		"base": "ring_mail",
		"name": "the Armour of Zhor",
		"slot": "chest",
		"ac": 7, "plus": 4, "ego": "cold_resistance",
		"color": Color(0.50, 0.80, 1.00),
		"min_depth": 11,
		"desc": "Once worn by an archmage who laughed off blizzards.",
	},
	"unrand_deep_dwarf_crown": {
		"kind": "armor",
		"base": "helmet",
		"name": "the Deep Dwarf Crown",
		"slot": "helm",
		"ac": 2, "plus": 3, "ego": "see_invisible",
		"color": Color(0.85, 0.75, 0.35),
		"min_depth": 9,
		"desc": "A brass circlet that reveals hidden things.",
	},
	"unrand_black_knights_horse": {
		"kind": "armor",
		"base": "boots",
		"name": "the Black Knight's Barding",
		"slot": "boots",
		"ac": 4, "plus": 4, "ego": "rampaging",
		"color": Color(0.15, 0.10, 0.20),
		"min_depth": 12,
		"desc": "Charges at foes on its own momentum.",
	},

	# --- Ring ---
	"unrand_ring_of_flames": {
		"kind": "ring",
		"name": "the Ring of Flames",
		"color": Color(1.00, 0.45, 0.15),
		"min_depth": 9,
		"slot": "ring",
		"desc": "Wreathes the wearer in a mantle of fire — fire-immune, cold-weak.",
		"props": {"fire": 2, "cold": -1, "spellpower": 3, "ev": 2},
	},

	# --- Amulets ---
	"unrand_amulet_of_the_air": {
		"kind": "amulet",
		"name": "the Amulet of the Air",
		"color": Color(0.75, 0.95, 1.00),
		"min_depth": 10,
		"slot": "amulet",
		"base": "amulet_regeneration",
		"desc": "The wearer breathes easy and moves with the wind at their back.",
		"props": {"dex": 2, "ev": 3, "stealth": 2},
	},
	"unrand_amulet_of_the_firebrand": {
		"kind": "amulet",
		"name": "the Firebrand Amulet",
		"color": Color(1.00, 0.55, 0.20),
		"min_depth": 11,
		"slot": "amulet",
		"base": "amulet_magic_mastery",
		"desc": "Blazing power flows into the wearer's spells — at a cost to caution.",
		"props": {"fire": 1, "spellpower": 4, "slaying": 2},
	},
	"unrand_quadruple_strike": {
		"kind": "weapon",
		"base": "morningstar",
		"name": "the Four-Pronged Morningstar",
		"dmg": 14, "skill": "mace", "delay": 1.6,
		"plus": 5, "brand": "vorpal",
		"color": Color(0.85, 0.45, 0.20),
		"min_depth": 10,
		"desc": "Four spiked heads strike in perfect unison.",
	},

	# ---------------- WAVE 4 (+15, session 15) ----------------
	# --- Legendary weapons ---
	"unrand_eos": {
		"kind": "weapon",
		"base": "longsword",
		"name": "the Sword of Eos",
		"dmg": 13, "skill": "long_blade", "delay": 1.4,
		"plus": 7, "brand": "flaming",
		"color": Color(1.00, 0.85, 0.55),
		"min_depth": 15,
		"desc": "A blade forged at the edge of dawn. Its light sears the wicked.",
	},
	"unrand_zephyr": {
		"kind": "weapon",
		"base": "longsword",
		"name": "Zephyr",
		"dmg": 10, "skill": "long_blade", "delay": 1.0,
		"plus": 6, "brand": "speed",
		"color": Color(0.75, 0.95, 1.00),
		"min_depth": 11,
		"desc": "A silver blade that sings in the wind — never stops moving.",
	},
	"unrand_bloodbane": {
		"kind": "weapon",
		"base": "longsword",
		"name": "Bloodbane",
		"dmg": 12, "skill": "long_blade", "delay": 1.4,
		"plus": 5, "brand": "draining",
		"color": Color(0.85, 0.15, 0.15),
		"min_depth": 10,
		"desc": "Drinks vitality from its victims with each strike.",
	},
	"unrand_deatrh": {
		"kind": "weapon",
		"base": "scythe",
		"name": "Death's Harvest",
		"dmg": 16, "skill": "polearm", "delay": 1.8,
		"plus": 6, "brand": "reaping",
		"color": Color(0.25, 0.15, 0.35),
		"min_depth": 14,
		"desc": "Each fallen foe rises briefly to serve the reaper.",
	},
	"unrand_chilperic": {
		"kind": "weapon",
		"base": "katana",
		"name": "Chilperic's Blade",
		"dmg": 14, "skill": "long_blade", "delay": 1.3,
		"plus": 5, "brand": "protection",
		"color": Color(0.65, 0.85, 0.50),
		"min_depth": 12,
		"desc": "Tempered to shield the wielder as it cuts.",
	},
	"unrand_trident_of_storms": {
		"kind": "weapon",
		"base": "trident",
		"name": "the Trident of the Storms",
		"dmg": 15, "skill": "polearm", "delay": 1.5,
		"plus": 5, "brand": "electrocution",
		"color": Color(0.55, 0.75, 1.00),
		"min_depth": 12,
		"desc": "Lightning crackles along its three tines.",
	},
	"unrand_serpents_lash": {
		"kind": "weapon",
		"base": "whip",
		"name": "the Serpent's Lash",
		"dmg": 8, "skill": "mace", "delay": 1.0,
		"plus": 5, "brand": "venom",
		"color": Color(0.55, 0.85, 0.30),
		"min_depth": 8,
		"desc": "Reach and bite in a single motion.",
	},
	"unrand_eclipse": {
		"kind": "weapon",
		"base": "morningstar",
		"name": "Eclipse",
		"dmg": 13, "skill": "mace", "delay": 1.5,
		"plus": 6, "brand": "pain",
		"color": Color(0.15, 0.10, 0.25),
		"min_depth": 13,
		"desc": "Its head is wreathed in a perpetual darkness.",
	},

	# --- Legendary armor ---
	"unrand_dragonhide": {
		"kind": "armor",
		"base": "scale_mail",
		"name": "the Dragonhide of Xom",
		"slot": "chest",
		"ac": 6, "plus": 5, "ego": "resistance",
		"color": Color(0.85, 0.30, 0.55),
		"min_depth": 14,
		"desc": "Scales of every color — Xom enjoyed the joke.",
	},
	"unrand_lord_armor": {
		"kind": "armor",
		"base": "plate_armour",
		"name": "the Lord's Plate",
		"slot": "chest",
		"ac": 12, "plus": 5, "ego": "positive_energy",
		"color": Color(0.85, 0.80, 0.45),
		"min_depth": 14,
		"desc": "A noble's plate — blessed to repel the undead.",
	},
	"unrand_cloak_of_flash": {
		"kind": "armor",
		"base": "cloak",
		"name": "the Cloak of Flash",
		"slot": "cloak",
		"ac": 1, "plus": 3, "ego": "shadows",
		"color": Color(0.85, 0.85, 1.00),
		"min_depth": 10,
		"desc": "A silver cloak that shimmers even in deep gloom.",
	},
	"unrand_boots_of_the_spider_queen": {
		"kind": "armor",
		"base": "boots",
		"name": "the Spider Queen's Boots",
		"slot": "boots",
		"ac": 1, "plus": 3, "ego": "jumping",
		"color": Color(0.35, 0.25, 0.15),
		"min_depth": 10,
		"desc": "Sticky-soled; leap across gaps that would break a giant's legs.",
	},
	"unrand_gauntlets_of_rage": {
		"kind": "armor",
		"base": "gloves",
		"name": "the Gauntlets of Rage",
		"slot": "gloves",
		"ac": 2, "plus": 4, "ego": "infusion",
		"color": Color(0.75, 0.25, 0.25),
		"min_depth": 11,
		"desc": "Armored fists that burn MP into raw force.",
	},

	# --- Legendary jewellery ---
	"unrand_ring_of_robustness": {
		"kind": "ring",
		"name": "the Ring of Robustness",
		"color": Color(0.85, 0.65, 0.25),
		"min_depth": 10,
		"slot": "ring",
		"desc": "A brass ring that thickens the wearer's hide.",
		"props": {"ac": 4, "str": 1, "hp": 15},
	},
	"unrand_amulet_of_four_winds": {
		"kind": "amulet",
		"name": "the Amulet of the Four Winds",
		"color": Color(0.65, 0.95, 0.95),
		"min_depth": 12,
		"slot": "amulet",
		"base": "amulet_regeneration",
		"desc": "Embossed with the four cardinal spirits — grants breath and motion.",
		"props": {"ev": 4, "dex": 2, "mp_max": 5, "stealth": 1},
	},
	# ---------------- WAVE 2 WEAPONS ----------------
	"unrand_autumn_katana": {
		"kind": "weapon",
		"base": "katana",
		"name": "the Autumn Katana",
		"dmg": 11, "skill": "long_blade", "delay": 1.3,
		"plus": 6, "brand": "vorpal",
		"color": Color(0.95, 0.65, 0.25),
		"min_depth": 9,
		"desc": "A blade that cuts as though every target were a falling leaf.",
	},
	"unrand_whistling_sword": {
		"kind": "weapon",
		"base": "longsword",
		"name": "the Whistling Sword",
		"dmg": 9, "skill": "long_blade", "delay": 1.2,
		"plus": 4, "brand": "electrocution",
		"color": Color(0.65, 0.95, 1.00),
		"min_depth": 6,
		"desc": "Air rushes past the edge in a shrill whistle on every swing.",
	},
	"unrand_undeadhunter": {
		"kind": "weapon",
		"base": "flail",
		"name": "Undeadhunter",
		"dmg": 10, "skill": "mace", "delay": 1.5,
		"plus": 5, "brand": "holy_wrath",
		"color": Color(1.00, 0.95, 0.70),
		"min_depth": 9,
		"desc": "A heirloom flail that makes the restless dead lie down again.",
	},
	"unrand_captains_cutlass": {
		"kind": "weapon",
		"base": "saber",
		"name": "the Captain's Cutlass",
		"dmg": 8, "skill": "short_blade", "delay": 1.1,
		"plus": 4, "brand": "reaping",
		"color": Color(0.80, 0.80, 0.90),
		"min_depth": 7,
		"desc": "Claimed from a pirate king — slain foes rise briefly at your side.",
	},
	"unrand_jihad": {
		"kind": "weapon",
		"base": "longsword",
		"name": "Jihad",
		"dmg": 10, "skill": "long_blade", "delay": 1.3,
		"plus": 6, "brand": "holy_wrath",
		"color": Color(1.00, 0.85, 0.35),
		"min_depth": 10,
		"desc": "A zealot's blade, burning brighter near the wicked.",
	},
	"unrand_staff_of_olgreb": {
		"kind": "weapon",
		"base": "gnarled_staff",
		"name": "the Staff of Olgreb",
		"dmg": 7, "skill": "staff", "delay": 1.3,
		"plus": 3, "brand": "venom",
		"color": Color(0.45, 0.85, 0.25),
		"min_depth": 7,
		"desc": "A green-twisted staff that drips poison from its grain.",
	},
	"unrand_asmodeus_scourge": {
		"kind": "weapon",
		"base": "whip",
		"name": "the Scourge of Asmodeus",
		"dmg": 9, "skill": "mace", "delay": 1.1,
		"plus": 5, "brand": "flaming",
		"color": Color(1.00, 0.35, 0.15),
		"min_depth": 13,
		"desc": "Nine flame-wound strands. Wielded once by a demon-prince.",
	},
	"unrand_morg": {
		"kind": "weapon",
		"base": "dagger",
		"name": "Morg",
		"dmg": 6, "skill": "short_blade", "delay": 0.9,
		"plus": 3, "brand": "pain",
		"color": Color(0.60, 0.10, 0.35),
		"min_depth": 5,
		"desc": "A black dagger that drinks from the wielder as it drinks from the target.",
	},
	"unrand_axe_of_woe": {
		"kind": "weapon",
		"base": "battleaxe",
		"name": "the Axe of Woe",
		"dmg": 14, "skill": "axe", "delay": 1.6,
		"plus": 5, "brand": "drain",
		"color": Color(0.55, 0.30, 0.55),
		"min_depth": 10,
		"desc": "An executioner's axe that drains the vigour of anything it bites.",
	},
	"unrand_arga": {
		"kind": "weapon",
		"base": "trident",
		"name": "Arga",
		"dmg": 10, "skill": "polearm", "delay": 1.4,
		"plus": 4, "brand": "freezing",
		"color": Color(0.60, 0.85, 1.00),
		"min_depth": 8,
		"desc": "A hunting trident forged for the leviathans of cold seas.",
	},
	"unrand_elemental_staff": {
		"kind": "weapon",
		"base": "crystal_staff",
		"name": "the Elemental Staff",
		"dmg": 9, "skill": "staff", "delay": 1.3,
		"plus": 4, "brand": "chaos",
		"color": Color(0.85, 0.65, 1.00),
		"min_depth": 12,
		"desc": "A staff of changing hues, echoing the four primal schools.",
	},
	"unrand_ignition_hammer": {
		"kind": "weapon",
		"base": "mace",
		"name": "the Ignition Hammer",
		"dmg": 10, "skill": "mace", "delay": 1.4,
		"plus": 6, "brand": "flaming",
		"color": Color(1.00, 0.55, 0.20),
		"min_depth": 9,
		"desc": "Each impact strikes a spark that lingers on armour and stone.",
	},
	# ---------------- WAVE 2 ARMOR ----------------
	"unrand_bullseye_buckler": {
		"kind": "armor",
		"slot": "shield",
		"name": "the Bullseye Buckler",
		"ac": 3, "plus": 3, "ego": "reflection",
		"color": Color(0.95, 0.40, 0.25),
		"min_depth": 8,
		"desc": "A round shield painted with a target — somehow it draws and deflects shots.",
	},
	"unrand_invisibility_cloak": {
		"kind": "armor",
		"slot": "cloak",
		"name": "the Cloak of Starlight",
		"ac": 1, "plus": 2, "ego": "stealth",
		"color": Color(0.25, 0.30, 0.55),
		"min_depth": 7,
		"desc": "A cloak strewn with faint pinpricks of light that fade when still.",
	},
	"unrand_helmet_of_serafin": {
		"kind": "armor",
		"slot": "helm",
		"name": "the Helm of Serafin",
		"ac": 2, "plus": 2, "ego": "see_invisible",
		"color": Color(0.95, 0.90, 0.70),
		"min_depth": 9,
		"desc": "The angels that wore it left something seeing behind the eye slits.",
	},
	"unrand_gloves_of_bloody_knuckles": {
		"kind": "armor",
		"slot": "gloves",
		"name": "the Bloody Knuckles",
		"ac": 1, "plus": 3, "ego": "strength",
		"color": Color(0.65, 0.20, 0.20),
		"min_depth": 6,
		"desc": "Cracked leather gloves that still ache with old fights.",
	},
	"unrand_boots_of_the_war_plate": {
		"kind": "armor",
		"slot": "boots",
		"name": "the Boots of the Black Guard",
		"ac": 2, "plus": 2, "ego": "rampaging",
		"color": Color(0.25, 0.20, 0.30),
		"min_depth": 9,
		"desc": "Heavy sabatons that hunger to close ground with the enemy.",
	},
	"unrand_robe_of_misfortune": {
		"kind": "armor",
		"slot": "chest",
		"name": "the Robe of Misfortune",
		"ac": 2, "plus": -2, "ego": "willpower",
		"color": Color(0.45, 0.10, 0.25),
		"min_depth": 7,
		"desc": "Frayed silk sewn with inverted runes. Wards the mind at a cost.",
	},
	"unrand_scale_mail_of_warding": {
		"kind": "armor",
		"slot": "chest",
		"name": "the Scale Mail of Warding",
		"ac": 6, "plus": 3, "ego": "positive_energy",
		"color": Color(0.85, 0.90, 1.00),
		"min_depth": 10,
		"desc": "Silver scales etched with prayers against the cold grasp of death.",
	},
	"unrand_plate_of_the_sunborne": {
		"kind": "armor",
		"slot": "chest",
		"name": "the Plate of the Sunborne",
		"ac": 10, "plus": 4, "ego": "fire_resistance",
		"color": Color(1.00, 0.80, 0.35),
		"min_depth": 13,
		"desc": "A full plate harness warm to the touch, lined with summer gold.",
	},
	# ---------------- WAVE 2 RINGS ----------------
	"unrand_ring_of_the_mage": {
		"kind": "ring",
		"name": "the Ring of the Mage",
		"color": Color(0.65, 0.55, 0.95),
		"min_depth": 8,
		"props": {"int": 4, "mp_max": 6, "spellpower": 2},
		"desc": "A sapphire band that sings faintly when spells weave nearby.",
	},
	"unrand_ring_of_iron_resolve": {
		"kind": "ring",
		"name": "the Ring of Iron Resolve",
		"color": Color(0.55, 0.55, 0.60),
		"min_depth": 7,
		"props": {"ac": 3, "str": 2, "mr": 30},
		"desc": "A heavy iron ring that steadies every blow and every thought.",
	},
	"unrand_ring_of_the_ember": {
		"kind": "ring",
		"name": "the Ring of the Ember",
		"color": Color(1.00, 0.45, 0.15),
		"min_depth": 8,
		"props": {"slaying": 3, "fire": 1},
		"desc": "A copper band that glows softly in the dark.",
	},
	"unrand_ring_of_the_glacier": {
		"kind": "ring",
		"name": "the Ring of the Glacier",
		"color": Color(0.65, 0.90, 1.00),
		"min_depth": 8,
		"props": {"cold": 2, "ac": 2},
		"desc": "Cool to the touch. The skin beneath it never blisters with frost.",
	},
	"unrand_ring_of_swift_steps": {
		"kind": "ring",
		"name": "the Ring of Swift Steps",
		"color": Color(0.80, 1.00, 0.60),
		"min_depth": 9,
		"props": {"dex": 3, "ev": 3, "stealth": 2},
		"desc": "A slender ring that feels lighter than it should.",
	},
	"unrand_ring_of_envy": {
		"kind": "ring",
		"name": "the Ring of Envy",
		"color": Color(0.30, 0.85, 0.35),
		"min_depth": 11,
		"props": {"int": 3, "str": -2, "spellpower": 3},
		"desc": "Green-shining jade that whispers of ambition and bitter victories.",
	},
	# ---------------- WAVE 2 AMULETS ----------------
	"unrand_amulet_of_the_hearth": {
		"kind": "amulet",
		"name": "the Amulet of the Hearth",
		"color": Color(1.00, 0.55, 0.25),
		"min_depth": 8,
		"slot": "amulet",
		"base": "amulet_regeneration",
		"desc": "A warm brass amulet that soothes wounds with the memory of a fire.",
		"props": {"fire": 1, "hp_regen": 2},
	},
	"unrand_amulet_of_the_silent_choir": {
		"kind": "amulet",
		"name": "the Amulet of the Silent Choir",
		"color": Color(0.85, 0.80, 1.00),
		"min_depth": 11,
		"slot": "amulet",
		"base": "amulet_magic_mastery",
		"desc": "Voices hum at the edge of hearing. Spells come easier.",
		"props": {"spellpower": 4, "mp_regen": 1},
	},
	"unrand_amulet_of_the_last_hope": {
		"kind": "amulet",
		"name": "the Amulet of the Last Hope",
		"color": Color(1.00, 0.95, 0.70),
		"min_depth": 14,
		"slot": "amulet",
		"base": "amulet_guardian_spirit",
		"desc": "A survivor's charm. They say it carried its wearer through the Abyss.",
		"props": {"willpower": 40, "hp_max": 10},
	},
	# ---------------- WAVE 3 — slot coverage pass ----------------
	# Fills in under-represented slots (cloaks / gloves / boots / helms)
	# and rounds out weapon variety. Keeps the same schema as wave 2 —
	# brands and egos reuse existing registry handlers, no new code
	# paths required.
	"unrand_cloak_of_stormweaver": {
		"kind": "armor",
		"slot": "cloak",
		"name": "the Cloak of the Stormweaver",
		"ac": 2, "plus": 3, "ego": "stealth",
		"color": Color(0.55, 0.65, 1.00),
		"min_depth": 10,
		"desc": "Woven on a still morning, it moves like wind in still air.",
	},
	"unrand_cloak_of_the_thunderhead": {
		"kind": "armor",
		"slot": "cloak",
		"name": "the Cloak of the Thunderhead",
		"ac": 1, "plus": 2, "ego": "resistance",
		"color": Color(0.35, 0.45, 0.75),
		"min_depth": 9,
		"desc": "Thunder rolls somewhere inside the weave.",
	},
	"unrand_cloak_of_the_raven": {
		"kind": "armor",
		"slot": "cloak",
		"name": "the Cloak of the Raven",
		"ac": 1, "plus": 2, "ego": "stealth",
		"color": Color(0.08, 0.08, 0.14),
		"min_depth": 7,
		"desc": "Feathers shift when you look away.",
	},
	"unrand_gloves_of_the_typhoon": {
		"kind": "armor",
		"slot": "gloves",
		"name": "the Gauntlets of the Typhoon",
		"ac": 1, "plus": 3, "ego": "dexterity",
		"color": Color(0.50, 0.85, 1.00),
		"min_depth": 10,
		"desc": "Each swing pulls a small gale into its wake.",
	},
	"unrand_gloves_of_vorpal_grip": {
		"kind": "armor",
		"slot": "gloves",
		"name": "the Gauntlets of the Vorpal Grip",
		"ac": 2, "plus": 3, "ego": "strength",
		"color": Color(0.85, 0.75, 0.45),
		"min_depth": 9,
		"desc": "Knuckles sheathed in iron that hums faintly when you make a fist.",
	},
	"unrand_gloves_of_the_archer": {
		"kind": "armor",
		"slot": "gloves",
		"name": "the Gloves of the Archer",
		"ac": 1, "plus": 2, "ego": "archery",
		"color": Color(0.55, 0.40, 0.25),
		"min_depth": 7,
		"desc": "Worn leather. The fingertips are callused into the shape of a bowstring.",
	},
	"unrand_boots_of_wanderlust": {
		"kind": "armor",
		"slot": "boots",
		"name": "the Boots of Wanderlust",
		"ac": 1, "plus": 2, "ego": "stealth",
		"color": Color(0.60, 0.50, 0.35),
		"min_depth": 5,
		"desc": "Travel-worn. They have walked further than most have lived.",
	},
	"unrand_boots_of_the_skyborne": {
		"kind": "armor",
		"slot": "boots",
		"name": "the Boots of the Skyborne",
		"ac": 1, "plus": 3, "ego": "flying",
		"color": Color(0.70, 0.85, 1.00),
		"min_depth": 11,
		"desc": "Crafted from feather-metal. You barely feel the floor beneath you.",
	},
	"unrand_boots_of_the_warhawk": {
		"kind": "armor",
		"slot": "boots",
		"name": "the Boots of the Warhawk",
		"ac": 2, "plus": 3, "ego": "rampaging",
		"color": Color(0.80, 0.60, 0.20),
		"min_depth": 10,
		"desc": "Steel-toed and impatient. They want to be moving.",
	},
	"unrand_helm_of_the_mindseer": {
		"kind": "armor",
		"slot": "helm",
		"name": "the Helm of the Mindseer",
		"ac": 2, "plus": 3, "ego": "intelligence",
		"color": Color(0.65, 0.45, 0.95),
		"min_depth": 10,
		"desc": "Circlet of violet alloy. Ideas come faster while it rests on your brow.",
	},
	"unrand_helm_of_the_basilisk": {
		"kind": "armor",
		"slot": "helm",
		"name": "the Helm of the Basilisk",
		"ac": 3, "plus": 2, "ego": "see_invisible",
		"color": Color(0.55, 0.85, 0.45),
		"min_depth": 9,
		"desc": "Two polished gems flank the visor. They seem to study what you miss.",
	},
	"unrand_crown_of_bronze": {
		"kind": "armor",
		"slot": "helm",
		"name": "the Crown of Bronze",
		"ac": 3, "plus": 3, "ego": "willpower",
		"color": Color(0.75, 0.55, 0.25),
		"min_depth": 12,
		"desc": "Heavy, pitted, and older than the kingdom that forged it.",
	},
	"unrand_chain_mail_of_the_hunter": {
		"kind": "armor",
		"slot": "chest",
		"name": "the Chain Mail of the Hunter",
		"ac": 5, "plus": 3, "ego": "stealth",
		"color": Color(0.45, 0.50, 0.45),
		"min_depth": 9,
		"desc": "Links wrapped in muted cloth so they never clink.",
	},
	"unrand_robe_of_the_conclave": {
		"kind": "armor",
		"slot": "chest",
		"name": "the Robe of the Conclave",
		"ac": 2, "plus": 3, "ego": "archmagi",
		"color": Color(0.75, 0.55, 1.00),
		"min_depth": 12,
		"desc": "Indigo silk. The hem whispers half-finished incantations.",
	},
	"unrand_leather_of_the_rogue": {
		"kind": "armor",
		"slot": "chest",
		"name": "the Leather of the Silent Rogue",
		"ac": 4, "plus": 3, "ego": "stealth",
		"color": Color(0.30, 0.25, 0.20),
		"min_depth": 8,
		"desc": "Hardened leather, fitted close. Stitches muffled with beeswax.",
	},
	# ---------------- WAVE 3 — weapons ----------------
	"unrand_bladebreaker": {
		"kind": "weapon",
		"base": "waraxe",
		"name": "Bladebreaker",
		"dmg": 11, "skill": "axe", "delay": 1.5,
		"plus": 5, "brand": "antimagic",
		"color": Color(0.45, 0.40, 0.50),
		"min_depth": 10,
		"desc": "A heavy axe that feeds on the magic its victims try to summon.",
	},
	"unrand_tempest_spear": {
		"kind": "weapon",
		"base": "longspear",
		"name": "the Tempest Spear",
		"dmg": 10, "skill": "polearm", "delay": 1.3,
		"plus": 5, "brand": "electrocution",
		"color": Color(0.85, 0.95, 1.00),
		"min_depth": 9,
		"desc": "The haft crackles on every thrust.",
	},
	"unrand_quicksilver_dagger": {
		"kind": "weapon",
		"base": "dagger",
		"name": "the Quicksilver Dagger",
		"dmg": 6, "skill": "short_blade", "delay": 0.8,
		"plus": 5, "brand": "vorpal",
		"color": Color(0.85, 0.85, 0.95),
		"min_depth": 7,
		"desc": "The blade shifts in your grip as if unable to stay still.",
	},
	"unrand_glaive_of_prune": {
		"kind": "weapon",
		"base": "halberd",
		"name": "the Glaive of the Pruner",
		"dmg": 12, "skill": "polearm", "delay": 1.6,
		"plus": 4, "brand": "vorpal",
		"color": Color(0.55, 0.75, 0.35),
		"min_depth": 10,
		"desc": "Used to tend the gardens of a dead archmage. It has seen other work since.",
	},
	"unrand_flaming_scimitar": {
		"kind": "weapon",
		"base": "scimitar",
		"name": "the Scimitar of the Desert Sun",
		"dmg": 9, "skill": "long_blade", "delay": 1.2,
		"plus": 4, "brand": "flaming",
		"color": Color(1.00, 0.70, 0.25),
		"min_depth": 8,
		"desc": "A curved blade that shimmers as if viewed through heat.",
	},
	"unrand_icebrand_flail": {
		"kind": "weapon",
		"base": "morningstar",
		"name": "the Icebrand Flail",
		"dmg": 10, "skill": "mace", "delay": 1.4,
		"plus": 4, "brand": "freezing",
		"color": Color(0.60, 0.90, 1.00),
		"min_depth": 8,
		"desc": "The spiked head is permanently rimed with fresh frost.",
	},
	"unrand_venom_whip": {
		"kind": "weapon",
		"base": "whip",
		"name": "the Venomthorn Whip",
		"dmg": 7, "skill": "mace", "delay": 1.0,
		"plus": 4, "brand": "venom",
		"color": Color(0.45, 0.80, 0.25),
		"min_depth": 6,
		"desc": "Braided from a sacred serpent. Each strike drips poison.",
	},
	# ---------------- WAVE 3 — rings ----------------
	"unrand_ring_of_the_bloodmoon": {
		"kind": "ring",
		"name": "the Ring of the Bloodmoon",
		"color": Color(0.80, 0.15, 0.25),
		"min_depth": 10,
		"props": {"slaying": 4, "hp_max": 8, "str": 2},
		"desc": "Crimson band. It thrums on nights the moon runs red.",
	},
	"unrand_ring_of_the_chimera": {
		"kind": "ring",
		"name": "the Ring of the Chimera",
		"color": Color(0.85, 0.55, 0.85),
		"min_depth": 11,
		"props": {"fire": 1, "cold": 1, "poison": 1, "ac": 2},
		"desc": "Three inset stones — flame, ice, and venom — share one band.",
	},
	"unrand_ring_of_quiet_footsteps": {
		"kind": "ring",
		"name": "the Ring of Quiet Footsteps",
		"color": Color(0.55, 0.55, 0.40),
		"min_depth": 6,
		"props": {"stealth": 4, "dex": 2},
		"desc": "A simple tin band. Somehow, it hushes everything around you.",
	},
	"unrand_ring_of_the_unseen": {
		"kind": "ring",
		"name": "the Ring of the Unseen",
		"color": Color(0.35, 0.40, 0.55),
		"min_depth": 10,
		"props": {"stealth": 3, "ev": 3, "see_invis": 1},
		"desc": "The stone glints and fades. You half-forget you're wearing it.",
	},
	"unrand_ring_of_the_ancestor": {
		"kind": "ring",
		"name": "the Ring of the Ancestor",
		"color": Color(0.90, 0.80, 0.45),
		"min_depth": 12,
		"props": {"str": 2, "int": 2, "dex": 2, "hp_max": 10},
		"desc": "Worn thin by the generations who wore it before you.",
	},
	# ---------------- WAVE 3 — amulets ----------------
	"unrand_amulet_of_the_hunter": {
		"kind": "amulet",
		"name": "the Amulet of the Hunter",
		"color": Color(0.85, 0.60, 0.25),
		"min_depth": 9,
		"slot": "amulet",
		"base": "amulet_regeneration",
		"desc": "A trophy-set bone amulet. Blood warms it back to life.",
		"props": {"slaying": 3, "stealth": 2},
	},
	"unrand_amulet_of_the_archer_queen": {
		"kind": "amulet",
		"name": "the Amulet of the Archer Queen",
		"color": Color(0.70, 0.45, 0.95),
		"min_depth": 12,
		"slot": "amulet",
		"base": "amulet_magic_mastery",
		"desc": "A royal focus. Spellwork flows from it as from a still pool.",
		"props": {"spellpower": 3, "dex": 2, "mp_max": 4},
	},
	# ---------------- WAVE 4 — ranged + exotic weapons ----------------
	"unrand_punisher_bow": {
		"kind": "weapon",
		"base": "long_bow",
		"name": "the Punisher",
		"dmg": 14, "skill": "bow", "delay": 1.5,
		"plus": 5, "brand": "pain",
		"color": Color(0.55, 0.15, 0.35),
		"min_depth": 11,
		"desc": "A yew bow that drinks on a full draw.",
	},
	"unrand_windchaser_bow": {
		"kind": "weapon",
		"base": "short_bow",
		"name": "the Windchaser",
		"dmg": 9, "skill": "bow", "delay": 1.0,
		"plus": 5, "brand": "electrocution",
		"color": Color(0.75, 0.90, 1.00),
		"min_depth": 8,
		"desc": "Quicker than any storm it shoots into.",
	},
	"unrand_heavyhand_crossbow": {
		"kind": "weapon",
		"base": "crossbow",
		"name": "Heavyhand",
		"dmg": 13, "skill": "crossbow", "delay": 1.8,
		"plus": 5, "brand": "flaming",
		"color": Color(0.85, 0.45, 0.20),
		"min_depth": 10,
		"desc": "A siege crossbow. The bolts glow red before they leave the groove.",
	},
	"unrand_sniper_crossbow": {
		"kind": "weapon",
		"base": "crossbow",
		"name": "the Sniper",
		"dmg": 11, "skill": "crossbow", "delay": 1.6,
		"plus": 6, "brand": "vorpal",
		"color": Color(0.35, 0.40, 0.45),
		"min_depth": 9,
		"desc": "Precision-stocked. Misses are rare; grazing hits, rarer.",
	},
	"unrand_returning_boomerang": {
		"kind": "weapon",
		"base": "boomerang",
		"name": "the Returning Curve",
		"dmg": 6, "skill": "throwing", "delay": 1.0,
		"plus": 4, "brand": "flaming",
		"color": Color(0.85, 0.55, 0.25),
		"min_depth": 7,
		"desc": "It comes back. Warm.",
	},
	"unrand_spriggan_slingshot": {
		"kind": "weapon",
		"base": "slingshot",
		"name": "the Spriggan's Sling",
		"dmg": 5, "skill": "sling", "delay": 0.8,
		"plus": 5, "brand": "venom",
		"color": Color(0.45, 0.85, 0.35),
		"min_depth": 6,
		"desc": "The bands are twisted from creepers that never stop growing.",
	},
	"unrand_dagger_of_chaos": {
		"kind": "weapon",
		"base": "dagger",
		"name": "Chaosfang",
		"dmg": 6, "skill": "short_blade", "delay": 0.9,
		"plus": 5, "brand": "chaos",
		"color": Color(0.85, 0.55, 0.95),
		"min_depth": 9,
		"desc": "Never the same wound twice.",
	},
	"unrand_rapier_of_the_count": {
		"kind": "weapon",
		"base": "rapier",
		"name": "the Rapier of the Count",
		"dmg": 8, "skill": "short_blade", "delay": 1.0,
		"plus": 4, "brand": "drain",
		"color": Color(0.55, 0.20, 0.30),
		"min_depth": 9,
		"desc": "A noble's dueling blade. Each cut tastes a little life.",
	},
	"unrand_obsidian_cleaver": {
		"kind": "weapon",
		"base": "waraxe",
		"name": "the Obsidian Cleaver",
		"dmg": 12, "skill": "axe", "delay": 1.5,
		"plus": 4, "brand": "vorpal",
		"color": Color(0.15, 0.10, 0.20),
		"min_depth": 10,
		"desc": "A volcanic glass edge, impossibly sharp and impossibly cold.",
	},
	"unrand_ironshard_mace": {
		"kind": "weapon",
		"base": "morningstar",
		"name": "the Ironshard Mace",
		"dmg": 11, "skill": "mace", "delay": 1.5,
		"plus": 5, "brand": "vorpal",
		"color": Color(0.60, 0.60, 0.65),
		"min_depth": 10,
		"desc": "Spiked with fragments that break off and then re-grow.",
	},
	"unrand_moonlit_blade": {
		"kind": "weapon",
		"base": "longsword",
		"name": "the Moonlit Blade",
		"dmg": 10, "skill": "long_blade", "delay": 1.3,
		"plus": 5, "brand": "holy_wrath",
		"color": Color(0.85, 0.90, 1.00),
		"min_depth": 11,
		"desc": "Silvery. It glows a touch brighter where demons have walked.",
	},
	# ---------------- WAVE 4 — armour (mostly auxiliary slots) --------
	"unrand_cloak_of_serpents": {
		"kind": "armor",
		"slot": "cloak",
		"name": "the Cloak of Serpents",
		"ac": 1, "plus": 2, "ego": "poison_resistance",
		"color": Color(0.30, 0.65, 0.30),
		"min_depth": 8,
		"desc": "A mantle that hisses when the wearer moves against the wind.",
	},
	"unrand_gloves_of_steadiness": {
		"kind": "armor",
		"slot": "gloves",
		"name": "the Gloves of Steadiness",
		"ac": 1, "plus": 2, "ego": "infusion",
		"color": Color(0.45, 0.60, 0.85),
		"min_depth": 10,
		"desc": "Tight leather. Nothing shakes from a grip that wears them.",
	},
	"unrand_boots_of_the_pursuer": {
		"kind": "armor",
		"slot": "boots",
		"name": "the Boots of the Pursuer",
		"ac": 1, "plus": 3, "ego": "rampaging",
		"color": Color(0.65, 0.25, 0.25),
		"min_depth": 9,
		"desc": "They want to run. Toward anything moving.",
	},
	"unrand_helm_of_the_dwarven_king": {
		"kind": "armor",
		"slot": "helm",
		"name": "the Crown of the Dwarven King",
		"ac": 3, "plus": 4, "ego": "willpower",
		"color": Color(0.85, 0.65, 0.30),
		"min_depth": 12,
		"desc": "Heavy, pitted with old fights, still shining where it matters.",
	},
	"unrand_ring_mail_of_flame": {
		"kind": "armor",
		"slot": "chest",
		"name": "the Ring Mail of Flame",
		"ac": 4, "plus": 3, "ego": "fire_resistance",
		"color": Color(1.00, 0.50, 0.20),
		"min_depth": 9,
		"desc": "Rust-red rings that never cool. Warms you in every winter.",
	},
	"unrand_robe_of_the_sages": {
		"kind": "armor",
		"slot": "chest",
		"name": "the Robe of the Sages",
		"ac": 2, "plus": 3, "ego": "energy",
		"color": Color(0.85, 0.75, 1.00),
		"min_depth": 10,
		"desc": "A quiet violet. Thoughts return to you a breath after you think them.",
	},
	"unrand_kite_shield_of_the_tower": {
		"kind": "armor",
		"slot": "shield",
		"name": "the Kite Shield of the Tower",
		"ac": 5, "plus": 4, "ego": "protection",
		"color": Color(0.50, 0.55, 0.70),
		"min_depth": 11,
		"desc": "Heavy iron. Forged from a fallen citadel's front gate.",
	},
	"unrand_scarf_of_lightning": {
		"kind": "armor",
		"slot": "cloak",
		"name": "the Scarf of Lightning",
		"ac": 1, "plus": 2, "ego": "resistance",
		"color": Color(1.00, 0.95, 0.35),
		"min_depth": 10,
		"desc": "It crackles faintly in dry air. It crackles louder in wet.",
	},
	# ---------------- WAVE 4 — jewellery ------------------------------
	"unrand_ring_of_the_wyrm": {
		"kind": "ring",
		"name": "the Ring of the Wyrm",
		"color": Color(0.85, 0.55, 0.25),
		"min_depth": 11,
		"props": {"str": 3, "fire": 1, "ac": 2, "hp_max": 10},
		"desc": "Dragon-scale set in bronze. It breathes warmth into the finger.",
	},
	"unrand_ring_of_the_leviathan": {
		"kind": "ring",
		"name": "the Ring of the Leviathan",
		"color": Color(0.35, 0.55, 0.85),
		"min_depth": 11,
		"props": {"hp_max": 15, "str": 2, "ac": 3},
		"desc": "Heavy as a tooth pulled from the deep.",
	},
	"unrand_ring_of_the_spider_queen": {
		"kind": "ring",
		"name": "the Ring of the Spider Queen",
		"color": Color(0.45, 0.20, 0.45),
		"min_depth": 10,
		"props": {"dex": 3, "poison": 1, "stealth": 3},
		"desc": "Eight tiny legs chase each other around the band.",
	},
	"unrand_ring_of_quiet_fury": {
		"kind": "ring",
		"name": "the Ring of Quiet Fury",
		"color": Color(0.70, 0.15, 0.20),
		"min_depth": 10,
		"props": {"slaying": 4, "str": 2, "stealth": 2},
		"desc": "The metal is cold. The rage inside it is not.",
	},
	"unrand_ring_of_three_stars": {
		"kind": "ring",
		"name": "the Ring of Three Stars",
		"color": Color(0.95, 0.95, 0.85),
		"min_depth": 12,
		"props": {"mp_max": 8, "spellpower": 3, "int": 2, "mp_regen": 1},
		"desc": "Three tiny diamonds set in a perfect row. None of them dim.",
	},
	"unrand_amulet_of_the_unseen_sun": {
		"kind": "amulet",
		"name": "the Amulet of the Unseen Sun",
		"color": Color(1.00, 0.85, 0.35),
		"min_depth": 12,
		"slot": "amulet",
		"base": "amulet_faith",
		"desc": "Gold turned inward. Warmth arrives from nowhere.",
		"props": {"fire": 1, "piety_gain": 1, "hp_regen": 2},
	},
	"unrand_amulet_of_the_drowned": {
		"kind": "amulet",
		"name": "the Amulet of the Drowned",
		"color": Color(0.35, 0.60, 0.80),
		"min_depth": 11,
		"slot": "amulet",
		"base": "amulet_stasis",
		"desc": "A water-worn pendant. Memories that weren't yours surface briefly.",
		"props": {"cold": 1, "willpower": 30, "mp_max": 4},
	},
	"unrand_amulet_of_the_broken_mirror": {
		"kind": "amulet",
		"name": "the Amulet of the Broken Mirror",
		"color": Color(0.70, 0.70, 0.85),
		"min_depth": 13,
		"slot": "amulet",
		"base": "amulet_reflection",
		"desc": "Cracked glass in a silver frame. Reflections linger a heartbeat too long.",
		"props": {"sh": 3, "ev": 2, "willpower": 20},
	},
	# ---------------- WAVE 5 — final roster fill-in -------------------
	# Weapons targeting gaps: quick blades, demon-themed, translocation
	# flavour, more late-depth options.
	"unrand_sunset_dagger": {
		"kind": "weapon",
		"base": "quick_blade",
		"name": "the Sunset Dagger",
		"dmg": 5, "skill": "short_blade", "delay": 0.7,
		"plus": 6, "brand": "flaming",
		"color": Color(1.00, 0.55, 0.30),
		"min_depth": 10,
		"desc": "Warm to hold. Leaves streaks of orange where it moves.",
	},
	"unrand_starlight_blade": {
		"kind": "weapon",
		"base": "quick_blade",
		"name": "Starlight",
		"dmg": 5, "skill": "short_blade", "delay": 0.7,
		"plus": 5, "brand": "electrocution",
		"color": Color(0.85, 0.95, 1.00),
		"min_depth": 11,
		"desc": "Silver edge that never smudges. Light plays along it at night.",
	},
	"unrand_demon_whip_of_anguish": {
		"kind": "weapon",
		"base": "whip",
		"name": "the Demon Whip of Anguish",
		"dmg": 9, "skill": "mace", "delay": 1.1,
		"plus": 5, "brand": "pain",
		"color": Color(0.65, 0.10, 0.30),
		"min_depth": 12,
		"desc": "Knotted with sinew and regret.",
	},
	"unrand_demon_trident_of_flame": {
		"kind": "weapon",
		"base": "trident",
		"name": "the Demon Trident of Flame",
		"dmg": 11, "skill": "polearm", "delay": 1.4,
		"plus": 4, "brand": "flaming",
		"color": Color(1.00, 0.40, 0.15),
		"min_depth": 12,
		"desc": "Tines cast three pools of red light on the floor.",
	},
	"unrand_demon_blade_of_the_pit": {
		"kind": "weapon",
		"base": "demon_blade",
		"name": "the Demon Blade of the Pit",
		"dmg": 12, "skill": "long_blade", "delay": 1.3,
		"plus": 5, "brand": "drain",
		"color": Color(0.55, 0.10, 0.25),
		"min_depth": 13,
		"desc": "A jagged red curve. It drinks first, and remembers.",
	},
	"unrand_warper_blade": {
		"kind": "weapon",
		"base": "long_sword",
		"name": "the Warper's Blade",
		"dmg": 9, "skill": "long_blade", "delay": 1.2,
		"plus": 4, "brand": "distortion",
		"color": Color(0.60, 0.40, 0.95),
		"min_depth": 10,
		"desc": "Space wrinkles where the edge has been.",
	},
	"unrand_void_scythe": {
		"kind": "weapon",
		"base": "scythe",
		"name": "the Void Scythe",
		"dmg": 13, "skill": "polearm", "delay": 1.6,
		"plus": 4, "brand": "distortion",
		"color": Color(0.30, 0.15, 0.50),
		"min_depth": 12,
		"desc": "A curve of black silence. The air gives way around it.",
	},
	"unrand_executioner_axe": {
		"kind": "weapon",
		"base": "executioners_axe",
		"name": "the Bleeding Axe",
		"dmg": 17, "skill": "axe", "delay": 1.8,
		"plus": 5, "brand": "vorpal",
		"color": Color(0.60, 0.15, 0.20),
		"min_depth": 13,
		"desc": "The blade is always wet. Rain doesn't clean it.",
	},
	"unrand_triple_sword": {
		"kind": "weapon",
		"base": "triple_sword",
		"name": "the Triple Sword of Ruin",
		"dmg": 16, "skill": "long_blade", "delay": 1.7,
		"plus": 4, "brand": "vorpal",
		"color": Color(0.80, 0.75, 0.65),
		"min_depth": 14,
		"desc": "Three interlocked blades that sing past each other.",
	},
	"unrand_double_sword": {
		"kind": "weapon",
		"base": "double_sword",
		"name": "the Double Sword of the Twin",
		"dmg": 12, "skill": "long_blade", "delay": 1.4,
		"plus": 5, "brand": "electrocution",
		"color": Color(0.85, 0.85, 1.00),
		"min_depth": 12,
		"desc": "Two blades on one haft. The strike echoes in the hand.",
	},
	"unrand_lajatang_of_the_moon": {
		"kind": "weapon",
		"base": "lajatang",
		"name": "the Lajatang of the Moon",
		"dmg": 12, "skill": "staff", "delay": 1.3,
		"plus": 4, "brand": "freezing",
		"color": Color(0.75, 0.85, 1.00),
		"min_depth": 13,
		"desc": "Twin crescents that trace the lunar cycle when spun.",
	},
	"unrand_great_mace": {
		"kind": "weapon",
		"base": "dire_flail",
		"name": "the Brick",
		"dmg": 14, "skill": "mace", "delay": 1.7,
		"plus": 5, "brand": "vorpal",
		"color": Color(0.45, 0.45, 0.50),
		"min_depth": 11,
		"desc": "It's a wall. On a stick.",
	},
	# Armour wave 5 — more variety across all slots.
	"unrand_robe_of_the_night": {
		"kind": "armor",
		"slot": "chest",
		"name": "the Robe of the Night",
		"ac": 2, "plus": 3, "ego": "stealth",
		"color": Color(0.08, 0.05, 0.15),
		"min_depth": 10,
		"desc": "Deeper than black. It drinks the lanterns.",
	},
	"unrand_plate_of_iron_faith": {
		"kind": "armor",
		"slot": "chest",
		"name": "the Plate of Iron Faith",
		"ac": 10, "plus": 4, "ego": "willpower",
		"color": Color(0.60, 0.55, 0.55),
		"min_depth": 13,
		"desc": "Blessed during a siege that lasted years.",
	},
	"unrand_scale_of_the_sentinel": {
		"kind": "armor",
		"slot": "chest",
		"name": "the Scale Mail of the Sentinel",
		"ac": 6, "plus": 3, "ego": "see_invisible",
		"color": Color(0.65, 0.70, 0.60),
		"min_depth": 10,
		"desc": "Each scale bears a tiny open eye, scanning the dark.",
	},
	"unrand_buckler_of_the_shade": {
		"kind": "armor",
		"slot": "shield",
		"name": "the Buckler of the Shade",
		"ac": 3, "plus": 3, "ego": "stealth",
		"color": Color(0.30, 0.25, 0.40),
		"min_depth": 8,
		"desc": "A buckler that casts its own shadow across the wearer.",
	},
	"unrand_tower_of_warding": {
		"kind": "armor",
		"slot": "shield",
		"name": "the Tower Shield of Warding",
		"ac": 7, "plus": 4, "ego": "willpower",
		"color": Color(0.80, 0.80, 0.95),
		"min_depth": 13,
		"desc": "Sigils of protection inlaid in silver. They warm to the touch.",
	},
	"unrand_cloak_of_the_displaced": {
		"kind": "armor",
		"slot": "cloak",
		"name": "the Cloak of the Displaced",
		"ac": 1, "plus": 3, "ego": "repulsion",
		"color": Color(0.60, 0.60, 0.95),
		"min_depth": 11,
		"desc": "Things aimed at its wearer tend to miss by a finger's width.",
	},
	"unrand_gloves_of_reaching": {
		"kind": "armor",
		"slot": "gloves",
		"name": "the Gloves of Reaching",
		"ac": 1, "plus": 3, "ego": "strength",
		"color": Color(0.75, 0.55, 0.35),
		"min_depth": 10,
		"desc": "Knuckles worn smooth by grip after grip.",
	},
	"unrand_helm_of_the_minotaur": {
		"kind": "armor",
		"slot": "helm",
		"name": "the Helm of the Minotaur",
		"ac": 3, "plus": 3, "ego": "strength",
		"color": Color(0.55, 0.35, 0.20),
		"min_depth": 11,
		"desc": "Horn-pierced. The visor tracks along the brow of something long dead.",
	},
	"unrand_boots_of_the_walker": {
		"kind": "armor",
		"slot": "boots",
		"name": "the Boots of the Walker",
		"ac": 2, "plus": 3, "ego": "stealth",
		"color": Color(0.50, 0.40, 0.30),
		"min_depth": 9,
		"desc": "They know where you're going. They wish you wouldn't.",
	},
	"unrand_crystal_plate_of_resolve": {
		"kind": "armor",
		"slot": "chest",
		"name": "the Crystal Plate of Resolve",
		"ac": 12, "plus": 4, "ego": "resistance",
		"color": Color(0.85, 0.95, 1.00),
		"min_depth": 14,
		"desc": "Forged of arcane crystal. Cold to the touch, warmer in danger.",
	},
	# Rings wave 5.
	"unrand_ring_of_the_thunderclap": {
		"kind": "ring",
		"name": "the Ring of the Thunderclap",
		"color": Color(1.00, 1.00, 0.55),
		"min_depth": 11,
		"props": {"elec": 1, "slaying": 3, "dex": 2},
		"desc": "The stone is etched with a single bolt.",
	},
	"unrand_ring_of_the_ferromancer": {
		"kind": "ring",
		"name": "the Ring of the Ferromancer",
		"color": Color(0.55, 0.55, 0.65),
		"min_depth": 11,
		"props": {"ac": 4, "spellpower": 2, "str": 2},
		"desc": "Iron that doesn't rust and doesn't bend.",
	},
	"unrand_ring_of_the_gambler": {
		"kind": "ring",
		"name": "the Ring of the Gambler",
		"color": Color(0.85, 0.20, 0.35),
		"min_depth": 9,
		"props": {"slaying": 5, "ac": -2},
		"desc": "A brass band with dice etched into the shoulders.",
	},
	"unrand_ring_of_hidden_sight": {
		"kind": "ring",
		"name": "the Ring of Hidden Sight",
		"color": Color(0.60, 0.85, 0.90),
		"min_depth": 10,
		"props": {"see_invis": 1, "ev": 3, "stealth": 2},
		"desc": "A flicker of recognition runs up the finger.",
	},
	"unrand_ring_of_the_adept": {
		"kind": "ring",
		"name": "the Ring of the Adept",
		"color": Color(0.70, 0.55, 0.85),
		"min_depth": 11,
		"props": {"spellpower": 4, "int": 3},
		"desc": "Polished from a pupil's first successful casting.",
	},
	# Amulets wave 5.
	"unrand_amulet_of_the_wayfarer": {
		"kind": "amulet",
		"name": "the Amulet of the Wayfarer",
		"color": Color(0.60, 0.75, 0.55),
		"min_depth": 8,
		"slot": "amulet",
		"base": "amulet_regeneration",
		"desc": "A traveler's token. Feet rest easier, roads read truer.",
		"props": {"stealth": 2, "ev": 2, "hp_regen": 1},
	},
	"unrand_amulet_of_the_archmagus": {
		"kind": "amulet",
		"name": "the Amulet of the Archmagus",
		"color": Color(0.85, 0.45, 0.95),
		"min_depth": 14,
		"slot": "amulet",
		"base": "amulet_magic_mastery",
		"desc": "Worn by a wizard who never lost a duel.",
		"props": {"spellpower": 5, "int": 3, "mp_max": 8},
	},
	"unrand_amulet_of_the_phoenix": {
		"kind": "amulet",
		"name": "the Amulet of the Phoenix",
		"color": Color(1.00, 0.55, 0.25),
		"min_depth": 13,
		"slot": "amulet",
		"base": "amulet_guardian_spirit",
		"desc": "Warm and heavy. The feather inside is always new.",
		"props": {"fire": 2, "hp_max": 15, "hp_regen": 2},
	},
	"unrand_amulet_of_the_cold_star": {
		"kind": "amulet",
		"name": "the Amulet of the Cold Star",
		"color": Color(0.55, 0.80, 1.00),
		"min_depth": 12,
		"slot": "amulet",
		"base": "amulet_magic_mastery",
		"desc": "A distant point of blue light, always at winter's heart.",
		"props": {"cold": 2, "mp_max": 6, "int": 2},
	},
	"unrand_amulet_of_the_keeper": {
		"kind": "amulet",
		"name": "the Amulet of the Keeper",
		"color": Color(0.85, 0.80, 0.70),
		"min_depth": 11,
		"slot": "amulet",
		"base": "amulet_regeneration",
		"desc": "An old warder's charge. The dead keep their distance.",
		"props": {"neg": 1, "hp_max": 10, "willpower": 20},
	},
}


static func has(id: String) -> bool:
	return _UNRANDS.has(id)


static func get_info(id: String) -> Dictionary:
	var info: Dictionary = _UNRANDS.get(id, {})
	return info.duplicate() if not info.is_empty() else {}


static func all_ids() -> Array:
	return _UNRANDS.keys()


## Rolled floor-drop id for the current depth, or "" if none eligible.
## Each unrand has a min_depth gate; the selection is uniform among
## eligible entries so higher-floor unrands don't starve when depth
## ticks up.
static func roll_for_depth(depth: int) -> String:
	var pool: Array = []
	for id in _UNRANDS.keys():
		if int(_UNRANDS[id].get("min_depth", 0)) <= depth:
			pool.append(id)
	if pool.is_empty():
		return ""
	return String(pool[randi() % pool.size()])


## Build the FloorItem-ready item dict for an unrand id. Shape matches
## what WeaponRegistry / ArmorRegistry / RingRegistry consumers expect
## so the existing pickup + equip + info-tooltip paths don't care that
## this is an artefact instead of a rolled base item.
static func make_item(id: String) -> Dictionary:
	var info: Dictionary = get_info(id)
	if info.is_empty():
		return {}
	var kind: String = String(info.get("kind", ""))
	var out: Dictionary = {
		"id": id,
		"name": String(info.get("name", id)),
		"kind": kind,
		"color": info.get("color", Color.WHITE),
		"unrand": true,
	}
	match kind:
		"weapon":
			out["plus"] = int(info.get("plus", 0))
			# The _weapon_brand_<id> meta the melee code reads is hung
			# on the player when the weapon equips; FloorItem carries
			# the intended brand in `brand` so Player.equip_weapon can
			# apply it.
			if info.has("brand"):
				out["brand"] = String(info["brand"])
		"armor":
			out["slot"] = String(info.get("slot", "chest"))
			out["ac"] = int(info.get("ac", 0))
			out["plus"] = int(info.get("plus", 0))
			if info.has("ego"):
				out["ego"] = String(info["ego"])
		"ring":
			out["slot"] = "ring"
			out["props"] = info.get("props", {})
			out["desc"] = String(info.get("desc", ""))
		"amulet":
			out["slot"] = "amulet"
			out["props"] = info.get("props", {})
			if info.has("base"):
				out["base"] = String(info["base"])
			out["desc"] = String(info.get("desc", ""))
	return out
